myblog/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="home"),
    path('list', views.PostsListView.as_view(), name='post_list'),
    path('posts/<int:post_id>/', views.post_detail, name="post_detail"),
]

# getでviews.py に送る場合
# path('posts/<int:pk>/', views.post_detail, name="post_detail")

myblog/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    published = models.DateTimeField()
    image = models.ImageField(upload_to='media/')
    body = models.TextField()

    def __str__(self):
        return self.title


    def summary(self):
        return self.body[:30]

myblog/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView
from .models import Post

# 何も入っていないrequestにhtmlを添えて返したあげる
def index(request):
    # return HttpResponse('Hello World! このページはインデックスや')
    posts = Post.objects.order_by('-published')
    return render(request, 'posts/index.html', {'posts': posts})

class PostsListView(ListView):
    model = Post
    template_name = "posts/list.html"

    # 検索機能
    def get_queryset(self):
        queryset = Post.objects.all()
        if 'query' in self.request.GET:
            qs = self.request.GET['query']
            queryset = queryset.filter(title__contains=qs)
        return queryset

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})

myblog/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>NMブログ</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand ml-4" href="#">NMのブログ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'posts:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'posts:post_list' %}" method='get'>
            <input class="form-control mr-sm-2" name='query' type="search" placeholder="キーワードで探す" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
{% block content %}
  
{% endblock content %}
<footer class="footer text-center py-2 theme-bg-dark">
		   
  <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
    <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by NM</small>

</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

myblog/posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center mt-3">ようこそ、NMのブログへ！</h1>
    {% load static %}
    <img src="{% static 'posts/shoe.jpeg' %}" class="img-fluid rounded mx-auto d-block" style="max-height: 200px;">


    <h3>最新の投稿</h3>
    {% for post in posts.all %}
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container">
            <div class="item mb-5">
                <div class="media">
                    <img class="mr-3 img-fluid rounded post-thumb d-none d-md-flex" src="{{ post.image.url }}" alt="image" style='width: 200px;'>
                    <div class="media-body">
                        <h3 class="title mb-1"><a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a></h3>
                        <div class="meta mb-1"><span class="date">{{ post.published }}</span><span class="time">： 1 min read</span></div>
                        <div class="intro">{{ post.summary }}</div>
                        <a class="more-link" href="{% url 'posts:post_detail' post.id %}">Read more &rarr;</a>
                    </div><!--//media-body-->
                </div><!--//media-->
            </div><!--//item-->            
        </div>
        <hr>
    </section>

    {% endfor %}
</div>
{% endblock content %}

myblog/posts/templates/posts/list.html
{% extends 'posts/base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center mt-3">ようこそ、NMのブログへ！</h1>
    {% load static %}
    <img src="{% static 'posts/shoe.jpeg' %}" class="img-fluid rounded mx-auto d-block" style="max-height: 200px;">


    <h3>最新の投稿</h3>
    {% for post in object_list %}
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container">
            <div class="item mb-5">
                <div class="media">
                    <img class="mr-3 img-fluid rounded post-thumb d-none d-md-flex" src="{{ post.image.url }}" alt="image" style='width: 200px;'>
                    <div class="media-body">
                        <h3 class="title mb-1"><a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a></h3>
                        <div class="meta mb-1"><span class="date">{{ post.published }}</span><span class="time">： 1 min read</span></div>
                        <div class="intro">{{ post.summary }}</div>
                        <a class="more-link" href="{% url 'posts:post_detail' post.id %}">Read more &rarr;</a>
                    </div><!--//media-body-->
                </div><!--//media-->
            </div><!--//item-->            
        </div>
        <hr>
    </section>

    {% endfor %}
</div>
{% endblock content %}

myblog/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}
{% block content %}
<article class="about-section py-5">
    <div class="container">
        <h2 class="title mb-3">{{ post.title }}</h2>
        
        <p>{{ post.published }}</p>
        <figure><img class="img-fluid" src="{{ post.image.url }}" alt="image" style='max-width: 500px;'></figure>
        <h5 class="mt-5">Contents</h5>
        <p>{{ post.body }}</p>
        <h5 class="mt-5">Experiences</h5>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto, commodi optio ea suscipit maxime illum voluptatem. Unde sequi, reiciendis, necessitatibus accusamus ipsum sapiente dignissimos ad soluta dolore totam sunt laudantium.</p>
        <h5 class="mt-5">thoughts</h5>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Atque sit exercitationem architecto delectus ex natus, nihil vero accusantium magni assumenda nemo aperiam est consequuntur dolorum repudiandae totam voluptatibus nobis quisquam.</p>
    </div>
</article>
{% endblock content %}